# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configuration
changelog:
  exclude:
    authors:
      - 'dependabot'
  categories:
    - title: 'New Features'
      labels:
        - 'type: feature ✨'
    - title: 'Improved'
      labels:
        - 'type: docs 📋'
        - 'type: style 🎨'
        - 'type: refactor 🔧'
    - title: 'Fixed'
      labels:
        - 'type: bug(fix) 🐞'
    - title: 'Other Changes'
      labels:
        - '*'
